### ISSUE TITLE
What is the content of pickle file?

### ISSUE THREAD

**Issue by 12345data** [andersgom/norep-app#1]
You have used a csv file and trained using KNN. What is the content of it? Didn't find any csv files in the project files. Can you you provide the details?

**Comment by andersgom** [comment]
The pickle file contains the KNN model, which I trained using the data from manually labelled images. I decided not to share the CSV files, but I generated them using a notebook available in the Mediapipe documentation that guided me with the pose classification. The data are the pose landmarks of each image and its label.
